# Continuous Control

---

You are welcome to use this coding environment to train your agent for the project.  Follow the instructions below to get started!

### 1. Start the Environment

Run the next code cell to install a few packages.  This line will take a few minutes to run!

In [1]:
!pip -q install ./python

ERROR: Invalid requirement: './python'
Hint: It looks like a path. File './python' does not exist.


The environments corresponding to both versions of the environment are already saved in the Workspace and can be accessed at the file paths provided below.  

Please select one of the two options below for loading the environment.

In [9]:
from unityagents import UnityEnvironment
import numpy as np

# select this option to load version 1 (with a single agent) of the environment
env = UnityEnvironment(file_name='/Users/anantnaw/Downloads/Reacher_one.app')

# select this option to load version 2 (with 20 agents) of the environment
# env = UnityEnvironment(file_name='/data/Reacher_Linux_NoVis/Reacher.x86_64')

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_speed -> 1.0
		goal_size -> 5.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [10]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

Run the code cell below to print some information about the environment.

In [11]:
# reset the environment
env_info = env.reset(train_mode=False)[brain_name]

# number of agents
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 1
Size of each action: 4
There are 1 agents. Each observes a state with length: 33
The state for the first agent looks like: [ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
  1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.75471878e+00 -1.00000000e+00
  5.55726671e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
 -1.68164849e-01]


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Note that **in this coding environment, you will not be able to watch the agents while they are training**, and you should set `train_mode=True` to restart the environment.

In [4]:
env_info = env.reset(train_mode=False)[brain_name]      # reset the environment    
states = env_info.vector_observations                  # get the current state (for each agent)
scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    actions = np.random.randn(num_agents, action_size)
    print (actions)# select an action (for each agent)
    actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1
    env_info = env.step(actions)[brain_name]           # send all actions to tne environment
    next_states = env_info.vector_observations         # get next state (for each agent)
    rewards = env_info.rewards                         # get reward (for each agent)
    dones = env_info.local_done                        # see if episode finished
    scores += env_info.rewards                         # update the score (for each agent)
    states = next_states                               # roll over states to next time step
    if np.any(dones):                                  # exit loop if episode finished
        break
print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

[[ 0.29973448 -1.74675612 -1.40948443 -0.37386376]]
[[-2.09671131 -1.85222624 -0.74618937 -1.25238089]]
[[1.40529785 0.05096608 1.62751501 0.26473517]]
[[ 0.52174188 -0.47143905  2.61001988  0.56018279]]
[[1.5045685  0.3570913  0.43683369 0.57674833]]
[[ 0.56574622 -0.1134556  -1.77120621 -1.18094506]]
[[-0.49015507 -0.28000014 -0.17443713  0.02771188]]
[[ 0.49425185 -1.47629517  0.94917192 -0.71598876]]
[[ 2.60955519 -1.08289442 -0.74342047 -1.5897674 ]]
[[-0.91206793  0.95840009 -1.69060819 -0.80863266]]
[[-1.92357042  0.75040097  0.99439677  0.88750202]]
[[-1.85283629 -1.42140003  1.56569111 -0.76976541]]
[[ 0.16593878 -1.17839592  1.0521416  -0.84399485]]
[[-1.42957659  0.04764169  1.28163775  1.09584237]]
[[ 1.00047512  0.2739042  -1.42815178 -0.21436516]]
[[-0.28229072  0.09104192  0.29563137 -1.25270092]]
[[ 0.62214015  0.4370191  -0.12604474  1.25587348]]
[[ 1.93076298 -0.2995931  -0.02243115  0.28642093]]
[[ 0.89036037  0.35888785  0.2165673  -1.85361534]]
[[-0.02534728  0.587

[[ 0.75854637 -2.03072877 -0.31745379 -0.28646797]]
[[ 0.26644431  1.43526659 -0.71608867 -1.66048003]]
[[ 1.77219953 -2.12408453 -0.69751596  0.72600028]]
[[ 0.06219819 -1.06122649  0.93804843  0.14895863]]
[[-1.35059384 -0.05048866  0.15696328 -1.21338247]]
[[ 0.70554117  0.40290325  0.30663184 -2.38312733]]
[[ 1.37513616  0.30182681 -1.33233962 -0.32565328]]
[[-0.0908469  -0.41172585 -0.75380675  0.36963246]]
[[ 0.22581491  1.49259202 -1.15056423  0.29558682]]
[[-0.57473228 -2.09905914 -0.35749305  0.52626213]]
[[-0.44910658  1.0064895  -0.11162472 -1.37610458]]
[[-0.26421898  0.09593535 -1.36165114  0.68498294]]
[[-1.72461823  1.15658968  0.31911674  0.07085502]]
[[-0.5450668   1.30015813 -0.07899867  0.64096452]]
[[ 0.83878601 -1.64472128 -0.44841446 -0.34343529]]
[[ 1.99155711 -0.22443815 -1.46642729 -0.80093097]]
[[-0.54604184 -0.12308375  1.19655674 -0.4797563 ]]
[[ 1.54011702  1.04457677 -0.32114877 -1.07400067]]
[[-1.59856224  0.62776968  0.44774952  0.15200946]]
[[-0.0693300

[[ 1.63347617  1.09920958 -0.46601078 -0.94337982]]
[[-0.86473906  1.41985392 -0.73791722 -1.09502457]]
[[-2.45506599 -0.03812707  1.13659902  0.10231628]]
[[ 1.38420433  0.98794788 -0.04107251 -1.59933935]]
[[ 0.08347689 -0.10955777  0.05436727 -1.28835412]]
[[-0.16084401  0.01945433  0.10316233 -2.73327399]]
[[ 0.14396941 -0.71617163 -0.54465433 -0.01550831]]
[[-1.42972625  0.16471209  0.26539318 -0.42911555]]
[[-1.16648057  0.89243931  0.46743302 -0.20200382]]
[[ 1.26163807 -0.80484003  1.36020201 -2.14786437]]
[[ 1.40861449 -1.12987481  0.47719582 -0.71836953]]
[[-1.7654417  -1.78108178 -1.68346452 -0.47531651]]
[[ 1.38160509  0.90759516  0.50613064 -0.45254416]]
[[ 0.44937681 -0.20427085  0.33981001 -0.29231671]]
[[ 0.10859188 -2.03107343  0.98685396  0.9257023 ]]
[[ 0.66280506  1.56808004  0.13190684 -0.11471191]]
[[-0.17409662 -0.54898246 -0.79864038  0.3178545 ]]
[[ 1.15066698 -1.25678518  0.23381881  0.2632957 ]]
[[ 0.46143364 -0.50156099  1.28516883  0.78714686]]
[[ 1.3841376

[[ 0.32485821  1.46028399  0.00924118 -1.21956924]]
[[-0.51873642  0.90147281  0.86958023  0.58973686]]
[[-0.60853048  0.31740301  2.70126614 -0.76110772]]
[[ 2.11838589  0.10927279  0.59904227 -2.15307884]]
[[ 1.42852829 -0.85656356  1.44675354  0.91090068]]
[[-0.27539956 -0.3444774  -0.63741339 -0.35681557]]
[[ 0.10315882  1.05506622 -0.21322916  1.77657767]]
[[-0.55735923 -0.67163058 -1.74025489 -0.58112017]]
[[-1.06275836  1.5891478  -1.14273014 -1.44768311]]
[[-0.55576326 -0.48745457 -0.05503268 -0.84340402]]
[[-0.29040603  0.42943348 -0.15937397 -1.90541283]]
[[ 1.53358807 -1.13810211 -0.4471604  -0.33389762]]
[[-0.17086552 -0.39816108 -0.1811289  -0.38852742]]
[[-0.86677066 -0.15862421  0.23450383  0.39607654]]
[[-0.14450182 -1.81982978 -1.27385868 -0.09921848]]
[[-0.60428285  0.28357496  0.97853089  2.29153202]]
[[-0.25190407  0.66319519 -0.20305922  0.59343559]]
[[-0.28527765 -1.48642422  0.19159437 -2.52183524]]
[[ 0.81781037  0.95869876  0.0083875  -0.57391604]]
[[ 1.0052719

[[-0.04189371 -0.35975952  0.80865674  1.36188689]]
[[-2.11912645 -0.95981747  0.90532201  1.2803793 ]]
[[ 1.27779267  0.70021484 -1.67298806  0.61228341]]
[[-1.1230931  -0.57390998  0.76093748  0.8139318 ]]
[[-0.03530302  0.16668881 -0.06823749  0.53477732]]
[[ 0.07401973  1.12227361  0.90053855 -0.23834159]]
[[-0.60338197  1.71080518  1.36136555 -0.20608571]]
[[-0.3090737  -1.4431922  -0.5923831  -0.76933645]]
[[ 0.06524968  1.20912309 -1.56011967 -0.58015575]]
[[-0.30465822 -1.41284873 -0.59506586 -0.86788936]]
[[-0.14741505 -0.87897292  0.09728199 -2.04152839]]
[[-0.39954143 -0.03998707  0.14020516 -1.4646322 ]]
[[ 0.4766619  -1.46672685  0.41679633 -0.27267637]]
[[0.78276607 0.76763099 0.43115275 0.00540814]]
[[ 3.11323719  0.36069026  0.09870359 -0.10013165]]
[[0.50756362 0.53500332 0.12489353 0.34949196]]
[[ 0.39232658  0.11050277  1.12653119 -1.70166093]]
[[ 1.95908935  0.28920338 -0.66360892  1.245563  ]]
[[ 0.72359979 -0.00972828  0.38996346 -0.2890736 ]]
[[-0.65294125 -0.256

[[-0.63295356  0.18835148  1.79761895 -0.19459448]]
[[1.62152121 1.80463441 0.77957832 2.11386741]]
[[-1.54673602  1.0171724   1.08675905 -0.58929963]]
[[ 0.89351222  0.61348621 -0.27961322  0.18877502]]
[[ 0.24218964  2.13005813 -0.1382936  -0.31883468]]
[[ 0.09310263  0.88629866 -1.12757038  0.75029169]]
[[ 1.90338492  2.07905247 -1.83449825  0.38218807]]
[[-0.46205693  0.40507217 -0.81951844 -1.62753323]]
[[-1.40828242  1.11794525 -0.11580931 -0.36604795]]
[[-0.89763946  0.55612588 -0.38811803 -0.81693864]]
[[ 0.36704481 -0.82271892  1.41213303 -1.27192722]]
[[ 2.22979929 -0.37404562 -0.98604729  0.67794863]]
[[-0.84169989 -0.91905289  2.05241334 -0.72245277]]
[[ 0.50060748  1.20346792 -0.2646175  -0.22258219]]
[[ 2.29334102 -0.56104983 -0.3367689  -1.39409224]]
[[-1.50448624  0.56249393  0.51860666 -1.71305235]]
[[ 0.83743209 -0.04676929  1.99161307 -1.43588323]]
[[ 0.57042361 -0.2374715   0.46163266  0.67380748]]
[[ 1.5782544  -1.22358047 -1.23817058  1.41887143]]
[[-1.99145406  0

[[ 0.39937663 -1.51776103  1.38117792 -1.20307086]]
[[-0.47963131  1.08390212  2.28963311  0.1756228 ]]
[[ 0.517023   -1.38492455 -0.68440162 -0.36539377]]
[[-0.99556194 -0.59606268  0.28695677  1.20382311]]
[[-1.17683312  0.92706548 -0.30586464 -0.02570583]]
[[-0.58219258 -0.99995739  1.11826854 -0.63352327]]
[[ 2.11279291  0.00545693 -1.43700386  2.19727448]]
[[-0.6835986   1.11054096  0.21546667  0.8723163 ]]
[[ 1.50407926 -1.26673344 -1.34225048 -0.6373225 ]]
[[ 1.2720393  -0.29377172 -0.49081418 -0.53002003]]
[[-1.22878915 -0.55673674 -1.650693    0.45374287]]
[[ 0.45302819 -0.2062099  -1.14443709 -0.9425422 ]]
[[-0.81927787 -1.19711063 -1.57006103 -1.3724555 ]]
[[ 1.28743022 -0.7006115  -1.67476091  0.68562331]]
[[ 1.06135946 -1.02192459  0.2213416  -1.67412911]]
[[ 0.69088444  0.28901861 -0.58868583  1.48364844]]
[[-0.64236463  0.57889708 -0.17218309  2.49528806]]
[[ 0.09278971  0.512358    1.02373615 -0.62551924]]
[[-0.6345589   1.30319786  0.50229781  1.57905259]]
[[ 0.5961723

## 4. Initialize model and the act function for the trained agent


In [12]:
from ddpg_agent import Agent
  
random_seed= 42
ddpg_agent = Agent(state_size, action_size, random_seed)
ddpg_agent.load_actor_inference("reacher_ddpg.pth")

256 256
256 256


In [13]:
scores = 0
env_info = env.reset(train_mode=False)[brain_name]      # reset the environment    
states = env_info.vector_observations                  # get the current state (for each agent)
scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    actions = ddpg_agent.act_inference(states)
    print (actions)# select an action (for each agent)                  # all actions between -1 and 1
    env_info = env.step(actions)[brain_name]           # send all actions to tne environment
    next_states = env_info.vector_observations         # get next state (for each agent)
    rewards = env_info.rewards                         # get reward (for each agent)
    dones = env_info.local_done                        # see if episode finished
    scores += env_info.rewards # update the score (for each agent)
    states = next_states                               # roll over states to next time step
    if np.any(dones):
       # exit loop if episode finished
        break
print('Total score (averaged over agents) this episode: {}'.format(scores))

[[ 1. -1. -1. -1.]]
[[ 1.         -1.         -0.99999964 -1.        ]]
[[ 1.        -0.9919506 -1.        -0.9999995]]
[[ 0.0468392   1.         -1.         -0.99990433]]
[[-0.19062944  1.         -1.         -0.99966806]]
[[ 0.9974557   1.         -1.         -0.96294904]]
[[ 0.9999696   1.         -0.99999994 -0.9960977 ]]
[[ 1.          1.         -0.99976677 -0.999659  ]]
[[ 1.         -0.71223456 -0.82114065 -0.99887407]]
[[1.        0.9994459 0.9853248 0.6143366]]
[[ 1.        -0.9999644  0.9946589  0.9997213]]
[[ 0.4604669   0.89666367 -0.91466004  0.99996626]]
[[-0.86006397 -0.999792    0.9988861   0.7170154 ]]
[[-0.96558297 -0.7567968   0.9887885  -0.9951887 ]]
[[ 0.96648437  0.3352329  -0.12732849  0.69016105]]
[[-0.71318334 -0.08409033  0.8439319  -0.9896696 ]]
[[ 0.99796796 -0.46324354 -0.972342    0.8090476 ]]
[[-0.795094   -0.69396675  0.94391936 -0.92688197]]
[[ 0.9960647   0.32087755 -0.9064159   0.9198694 ]]
[[ 0.9281932  -0.9970326   0.99620855 -0.98560506]]
[[ 0.743

[[ 0.60723126 -0.9238501  -0.80614394 -0.99996746]]
[[0.9910995 0.8341675 0.9112528 0.9996259]]
[[-0.07381052 -0.86426187 -0.59070385 -0.999996  ]]
[[ 0.9998948  -0.39973858  0.8238857   0.8299498 ]]
[[ 0.28076363 -0.6501283  -0.41664448 -0.99999714]]
[[0.9959371  0.48253328 0.39799282 0.02657335]]
[[ 0.9985856  -0.9496373  -0.21754938 -0.9879666 ]]
[[0.9976554  0.8773751  0.25624704 0.99999917]]
[[ 0.9064657  -0.68332666  0.46853092 -0.9769773 ]]
[[ 0.535902    0.70139426 -0.93697333  0.9992995 ]]
[[-0.13096817 -0.969222    0.9978376  -0.541331  ]]
[[ 0.997608   -0.82605094 -0.01988283 -0.2237238 ]]
[[0.92512566 0.87933606 0.5727674  0.99902153]]
[[ 0.8849497   0.3675516  -0.6667574  -0.99998564]]
[[ 0.9920357  -0.82718253  0.96206295  0.9917781 ]]
[[-0.53588223  0.9686233  -0.51888543 -0.9999767 ]]
[[ 0.99794686 -0.41253197  0.8726964   0.95756584]]
[[ 0.9063049   0.27108267 -0.03337159 -0.999997  ]]
[[ 0.98803204  0.5587373  -0.4763587   0.50551325]]
[[ 0.9002022  -0.9776487   0.969

[[-0.9999748  -0.96110916 -0.94618833 -0.9999794 ]]
[[ 0.99985003 -0.9194498   0.98415035  0.9242377 ]]
[[-0.99981564 -0.32364827 -0.9281446  -0.9999821 ]]
[[ 0.9999344  -0.10114907  0.9872692   0.9458073 ]]
[[-0.38104394 -0.9972757  -0.86173594 -0.9999992 ]]
[[ 0.99998766 -0.44731575  0.9770109   0.2770735 ]]
[[ 0.9759871  -0.99733895 -0.8872314  -0.9999741 ]]
[[0.9795176 0.963579  0.8706493 0.9989777]]
[[-0.8638566  -0.92091036 -0.84643596 -0.9999962 ]]
[[ 0.9999751  -0.65457475  0.9671509   0.99147624]]
[[ 0.44921207 -0.4094912  -0.5735881  -0.99999607]]
[[0.98133945 0.63177913 0.5766262  0.09537916]]
[[ 0.99217314 -0.9834395  -0.49391893 -0.9989275 ]]
[[0.9984654  0.27794597 0.51094925 0.9999928 ]]
[[ 0.08493751 -0.8003564  -0.24146134 -0.9992971 ]]
[[ 0.9996165  -0.8276943   0.46528348  0.9998589 ]]
[[-0.46126503  0.9001472  -0.34324348 -0.99649566]]
[[ 0.9997994  -0.96651155  0.7525372   0.9996154 ]]
[[ 0.65929145  0.72835606 -0.69002736 -0.9996065 ]]
[[ 0.99835956 -0.90600026  0

[[-0.58242434  0.18778151 -0.9617539  -0.9606489 ]]
[[ 0.99991286 -0.999993    0.9947915   0.9995782 ]]
[[ 0.86205846 -0.8987773  -0.83419526 -0.9869351 ]]
[[ 0.979643   -0.99494046  0.9071446   0.99726963]]
[[-0.9991133   0.40536693 -0.9726786  -0.9967736 ]]
[[ 0.999998   -0.99995506  0.99261904  0.9980597 ]]
[[-0.9969646  -0.9208257  -0.94806206 -0.99962246]]
[[ 0.99999857 -0.99690616  0.9925965   0.9981748 ]]
[[-0.9930887   0.05184485 -0.93373007 -0.9996246 ]]
[[ 0.99999887 -0.9759073   0.993757    0.9957252 ]]
[[-0.67428875  0.2689436  -0.9299548  -0.99989897]]
[[ 0.9999994  -0.99335647  0.9935155   0.953071  ]]
[[ 0.7971061  -0.83911335 -0.8669946  -0.99999106]]
[[0.98139966 0.99297667 0.8375914  0.98008996]]
[[-0.6809289 -0.5594657 -0.7196828 -0.999999 ]]
[[0.9999812  0.3882573  0.940047   0.25414777]]
[[ 0.9999655  -0.99968845 -0.29034144 -0.999989  ]]
[[ 0.99970746 -0.7254737  -0.3440059   0.8890665 ]]
[[-0.17383097  0.9954883   0.8827013  -0.9633255 ]]
[[ 0.99881774 -0.9818055

[[-0.30483297 -0.9910552  -0.85325676 -0.631174  ]]
[[ 0.39383903 -0.9303451  -0.67396444  0.93666804]]
[[ 0.3491205  -0.74973327  0.9849786   0.0022236 ]]
[[-0.99631226  0.9673969  -0.72071093 -0.7846774 ]]
[[ 0.99896    -0.9563907   0.9826693  -0.25950876]]
[[ 0.86765903 -0.22133636 -0.940161   -0.86368287]]
[[ 0.9873695  -0.9590143   0.9585359   0.96541995]]
[[ 0.23075482  0.83777684 -0.93714553 -0.9964392 ]]
[[ 0.98800635 -0.9995559   0.9421619  -0.10979664]]
[[-0.6971237 -0.9997915 -0.989822  -0.9945786]]
[[ 0.99999976 -0.99999934  0.9664014   0.9999244 ]]
[[-0.64417994 -0.99814016 -0.97248423 -0.98515147]]
[[ 1.        -0.9999849  0.9712565  0.9999851]]
[[-0.95078933 -0.8006451  -0.9888274  -0.95797575]]
[[ 0.9999998  -0.99598783  0.9528311   0.9999979 ]]
[[-0.8697444   0.9004265  -0.98806584 -0.543345  ]]
[[ 0.9999987  -0.9998      0.9674287   0.99551314]]
[[-0.66655034 -0.8228439  -0.96961045 -0.9997224 ]]
[[ 0.99999803 -0.8420193   0.967444    0.9995559 ]]
[[ 0.0644049   0.874

[[ 0.71213853 -0.9914145  -0.7480621  -0.5627863 ]]
[[-0.9717826  -0.9966487  -0.45828763  0.5559571 ]]
[[ 0.9980695  -0.9998594   0.99364173 -0.5393294 ]]
[[ 0.87837553 -0.9465576  -0.5063508  -0.42306414]]
[[ 0.02353881 -0.99293935 -0.6888023  -0.04868483]]
[[-0.90502995 -0.9848447  -0.57185423  0.3103159 ]]
[[ 0.9921648  -0.9996926   0.97676903  0.45614493]]
[[ 0.9717971  -0.99204993 -0.0570813  -0.91947216]]
[[ 0.5468957 -0.9334108 -0.8238031 -0.7508514]]
[[ 0.86347795 -0.9796266  -0.58329624  0.47269946]]
[[ 0.7247616 -0.8671811  0.9700274 -0.6521144]]
[[-0.8180416   0.67802626 -0.93957204 -0.7075286 ]]
[[ 0.99994504 -0.9999326   0.9946741   0.9899457 ]]
[[ 0.9979305  -0.7660751  -0.798121   -0.99624443]]
[[ 0.99863684 -0.93975437  0.9644993   0.85990584]]
[[ 0.90020347  0.32035273 -0.9040845  -0.9994313 ]]
[[ 0.9929659  -0.9353654   0.8912732  -0.24001798]]
[[ 0.02762811 -0.9940682  -0.98235357 -0.98195267]]
[[ 0.99967366 -0.99000525  0.78571516  0.9999759 ]]
[[-0.9990102   0.949

[[-0.9961411  -0.4278019  -0.96042204  0.44465837]]
[[-0.01801625 -0.9999144   0.9253737  -0.53729135]]
[[-0.83767766  0.7952177  -0.9796008   0.22693029]]
[[ 0.89779294 -0.9999817   0.00876789 -0.7820849 ]]
[[-0.99128026 -0.9797749  -0.9778231   0.33943358]]
[[ 0.994745   -0.9998819   0.91579336 -0.31418353]]
[[-0.22758923 -0.45461756 -0.9723134  -0.07530817]]
[[ 0.44185203 -0.9949632  -0.4785412   0.17887184]]
[[-0.93550557 -0.99936885  0.49433836  0.0853667 ]]
[[ 0.9985633  -0.9873877   0.6749178  -0.66196746]]
[[ 0.8504351   0.7109682  -0.90397054 -0.3095542 ]]
[[-0.93438566 -0.9993091  -0.93996286 -0.8146689 ]]
[[ 0.87469274 -0.9999547  -0.46561694  0.70787495]]
[[ 0.95749056 -0.99999887  0.9230497  -0.1452046 ]]
[[ 0.45209688 -0.99932665 -0.7307601  -0.9403207 ]]
[[ 0.48198062 -0.999716   -0.53908825  0.32678804]]
[[ 0.4532775  -0.9974163   0.97324044 -0.02373489]]
[[-0.9650189  -0.06698642 -0.90804017 -0.8155209 ]]
[[ 0.99956673 -0.99971277  0.9866973   0.9875335 ]]
[[ 0.9622156

When finished, you can close the environment.

In [8]:
env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  A few **important notes**:
- When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```
- To structure your work, you're welcome to work directly in this Jupyter notebook, or you might like to start over with a new file!  You can see the list of files in the workspace by clicking on **_Jupyter_** in the top left corner of the notebook.
- In this coding environment, you will not be able to watch the agents while they are training.  However, **_after training the agents_**, you can download the saved model weights to watch the agents on your own machine! 